name: Create Release + Publish

on:
  push:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Strip debug symbols
      run: strip target/release/oled_shmoled
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - with:
        tag_name: ${{ github.ref }}
        release_name: v${{ github.ref}}
        draft: false
        prerelease: false
    - name: Publish to crates.io
      run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish
